### DISCUSSION TITLE
HOWTO use replacements with more advanced regex?

### DISCUSSION THREAD

**Discussion by sdurrheimer** [miniscruff/changie#179] [Q&A] [answered]
Hi @miniscruff,

I'm trying the [`replacements`](https://changie.dev/config/replacements/) feature to change the version within my Helm `Chart.yaml` file.

The file presents itself as the following:
```yaml
version: 0.1.0

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-mysql
    version: ~8.8.8
    condition: mysql.enabled
```

If I use the following configuration, the main version and dependency version are changed:
```yaml
replacements:
- path: Chart.yaml
  find: 'version: .*'
  replace: 'version: {{.VersionNoPrefix}}'
```

But If I do the following to make sure the line strictly start with the `version` string without spaces in front of it, the replacement doesn't happen at all:
```yaml
replacements:
- path: Chart.yaml
  find: '^version: .*'
  replace: 'version: {{.VersionNoPrefix}}'
```

How can I make this work properly?

**Comment by miniscruff** [comment]
The second version works for me after copy pasting your Chart.yaml and replacements config. I don't see anything wrong and was not able to run into any issues myself.

**Reply by sdurrheimer** [reply]
Hum true, I tried to simplify the example for the sake of this question of not making it too verbose, but indeed does work with it (I should have verified it, sorry for that).

That being said it doesn't with the following complete file:
<details>Chart.yaml
<p>

```yaml
apiVersion: v2
name: cycloid
description: A Helm chart for Cycloid, the Hybrid Cloud DevOps Collaboration Platform
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.3.1"

kubeVersion: ">= 1.18.0 <= 1.22.0"

home: https://cycloid.io

sources:
  - https://github.com/cycloidio/ansible-cycloid-onprem

maintainers:
  - name: Cycloid DevOps team
    email: support@cycloid.io

icon: https://avatars.githubusercontent.com/u/14579210

keywords:
  - cycloid
  - devops
  - cloud
  - aws
  - gcp
  - azure
  - flexible-engine

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-mysql
    version: ~8.8.8
    condition: mysql.enabled

  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-redis
    version: ~15.4.1
    condition: redis.enabled

  - name: concourse
    repository: https://concourse-charts.storage.googleapis.com/
    tags:
      - concourse
    version: ~14.5.6
    condition: concourse.enabled

  - name: vault
    repository: https://helm.releases.hashicorp.com
    tags:
      - hashicorp-vault
    version: ~0.8.0
    condition: vault.enabled

# annotations:
#   artifacthub.io/prerelease: "{{IS_PRERELEASE}}"
```

</p>
</details>
