### DISCUSSION TITLE
Changelog subsection in addition to kinds

### DISCUSSION THREAD

**Discussion by emmyoop** [miniscruff/changie#219] [Ideas] [answered]
I just started to play with `changie` but what I've seen so far is great!  Looks like it might be able to help resolve 

I don't think this is possible with `changie` now, but would be happy to be corrected.  I want to give credit to my open source contributors with a `Contributors` section in my `CHANGELOG`.  It would be a section in addition to each `kind`. 

Something along the lines of this:

```
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html),
and is generated by [Changie](https://github.com/miniscruff/changie).

## my-repo 1.1.0 (January 01, 2022)

### Features
- Cool new thing that will be awesome. ([#1234](https://github.com/emmyoop/my-repo/issues/1234), [#4444](https://github.com/emmyoop/my-repo/pull/4444))

### Fixes
- Fixed something. ([#1234](https://github.com/emmyoop/my-repo/issues/1234), [#4487](https://github.com/emmyoop/my-repo/pull/4487))

Contributors:
- [@not-me](https://github.com/not-me) ([#4487](https://github.com/emmyoop/my-repo/pull/4487))
```

I think this is a pretty common scenario in open source.  If this isn't possible with `changie` currently, would you be open to adding this functionality?

**Comment by miniscruff** [comment]
Currently there is no option for this, you could add an extra custom input to add each contributor as part of each change sort of like: https://github.com/goreleaser/goreleaser/releases/tag/v1.3.0. But not the option of adding contributors with avatars at the bottom.

At the moment changie has no context to git as it works entirely from input so you would have to provide it the value of your github account. Changie could support this similar to how it does the body, maybe as an optional configuration but there are no plans for supporting it as of now.

I think it would be interesting to support this but it would have to be sort of agnostic to git and contributors as a whole. Which may sound weird but what if there was say a custom input for "githubAccount" on each change. Then a custom blocks section that looked sort of like:

```yaml
# purely hypothetical here don't get attached
custom:
- key: githubAccount
  type: string
  minLength: 2
# we would run the block format per change to create a block at the end.
# this would happen during the batch command.
blocks:
  - label: "Contributors"
    fields: 
    - "githubAccount" # could grab multiple?
    unique: true # not quite right if we support multiple fields as what would be unique then?
    sort: "asc" # would need to specify which field to sort by
    format: "- [@{{.accountName}}](https://github.com/{{.accountName}})"
```

There would probably be a few examples for common situations as it could be complex. 

This sort of format, although verbose, would support contributors along with other end of release notes things like counting the number of fixed bugs or total fixed changes. The query system would have to be refined and would probably turn into a bit of a mess but hard coding contributors is not really what I would want to do. 

Kind of rambling at this point so tl;dr you can add custom inputs per change, you can not add a custom block.

**Reply by emmyoop** [reply]
I was definitely thinking of having contributors enter their usernames via a custom field or something along that line, not pulling info from git.  I'm just starting to evaluate changie for my company and this is one piece (critical for us) that is missing.  The result of the conversation below with @rocktavious seems like it would meet our needs and be flexible for the future as well!

**Reply by miniscruff** [reply]
I am going through some designing this week and I have next week off so I hope to get something by then. Feel free to reach out or tag me if you have any more details on how your company or team might want to use changie.

**Comment by rocktavious** [comment]
Something like this would be really useful for my company too!

@miniscruff What if instead of it being so prescriptive you could just specify a custom footer to the generated change md file

```yaml
custom:
- key: githubAccount
  type: string
  minLength: 2
batch:
  footer: |
    Contributors:
    {{ range $item := .changes }}
       - [@{{$item.accountName}}](https://github.com/{{$accountName}})
    {{ end }}
```

This way its super flexible to any other kind of footer additions as well as possibly great for my custom usecase too.

Then it could also be easily extended to completely control the creation of the batch changelog with header, body and footer expression format - IE:

```yaml
batch:
  header:
  body:
  footer:
```

I don't love the "batch" name here if there is something better let me know.  I would be highly interested in implementing this for you!
