### DISCUSSION TITLE
Input on including the PR number in the changelog yaml.

### DISCUSSION THREAD

**Discussion by emmyoop** [miniscruff/changie#346] [General]
Wondering if anyone might have an idea of how to implement below for the best user experience.  This is more of an GitHub Actions question than strictly changie.

Within my custom fields, I want to include the PR number related to the change.

```yaml
custom:
  - key: Author
    label: GitHub Username(s) (separated by a single space if multiple)
    type: string
    minLength: 3
  - key: Issue
    label: GitHub Issue Number
    type: int
    minLength: 4
  - key: PR
    label: GitHub Pull Request Number
    type: int
    minLength: 4
```

The problem is I [audit](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/changelog-check.yml) if a changelog exists on the PR with GitHub actions so everyone gets a failed check when they open the PR since they cannot include the PR number before the PR exists.

This is obviously not stopping us from using changie.  There are work arounds - opening the PR in draft stops the check from running & generating the changie yaml with a fake PR number (or I could make it optional and it could then be blank) - but these don't feel great.

What I'd like is to auto populate the PR number with an action.  The problem here is we are an open source project that gets many community contributions from forks.  So I won't be able to just add a commit to the PR with the changelog modified.   I don't think I could do it after I merge into `main` (where I have control) because I would no longer have access to the PR number.

Any ideas on a solution here?
