### DISCUSSION TITLE
v1.11 Auto Mode

### DISCUSSION THREAD

**Discussion by miniscruff** [miniscruff/changie#443] [Show and tell]
v1.11 brings with it a new feature, "auto mode" https://github.com/miniscruff/changie/issues/439. To take advantage of this feature you can update your configuration to include what level of bumping ( major, minor or patch ) each kind should use. Then instead of saying `changie batch major/minor/patch` you can just use `changie batch auto`. 

If you are starting a new project, `init` will come defaulted with values for the predefined kinds.
Changie itself is using this new feature already, the config can be seen [here](https://github.com/miniscruff/changie/blob/main/.changie.yaml) as always.

Specifically the new options are part of `kinds`: 
```yaml
kinds:
  - label: Added
    auto: minor
  - label: Changed
    auto: major
  - label: Deprecated
    auto: patch
  - label: Removed
    auto: major
  - label: Fixed
    auto: patch
  - label: Security
    auto: patch
```

Here is the documentation for the new configuration: https://changie.dev/config/#kindconfig-auto
If you find any issues with this new feature, create an issue.

Note: Auto is also supported in `changie next` so you could output what the next version would be, if you were to `batch auto`.
Documentation may not be fully fleshed out at the moment so reach out if there is any confusion as it is improved over time.
