### DISCUSSION TITLE
Feeds builder

### DISCUSSION THREAD

**Discussion by miniscruff** [miniscruff/changie#452] [Ideas]
A potential feature idea I have been thinking about is using changie to generate a news feed ( atom, RSS, json feeds, etc ) that you would then host and allow users to subscribe to. This would take some configurations and "append" entries for each release using the generated release notes into an existing feed file. Or it could generate a separate `{version}.{feed name}.{feed-type}` file as part of batch, that together with a feed template or header generate a feed when merging. ( Probably a go template file to be honest )

The output would be sort of similar to the GitHub releases feed but more customizable. See Changies [releases feed](https://github.com/miniscruff/changie/releases.atom) or a [preview here](https://m.simplepie.org/?feed=https%3A%2F%2Fgithub.com%2Fminiscruff%2Fchangie%2Freleases.atom), to see your own projects feed the url path is: `https://github.com/:org/:project/releases.atom`.

Some vague hypothetical configurations could be:

```yaml
# default config
feeds:
- type: rss
  path: docs/static/feeds.rss
  template: feeds-template.rss # golang template file relative to changes dir
  entry:
    author: "email of author, maybe org email?"
    title: "Release {{.Version}}" # go template, probably similar to version header
    link: "https://changie.dev/changelog/#release-{{.Version}}"
    # other rss entry values with go templates and data types like change format
- type: atom
  # same as rss but for atom values
- type: jsonfeed
  # same as atom/rss but for jsonfeed
- type: ?
  # technically, feed here is just a template file with an array of all entries generated
  # so we could use it for anything else as well
```

I feel like creating some sort of `{VERSION}.{FEED-TYPE}.{FEED-EXT}` file for each batch, then when merging, in addition to merging the release notes to the root changelog, merge the feeds into a shared feed would be the way to go. There is also the case of migrating existing config values into its own feed structure, like `type: changelog/release notes/semver` but it is kind of baked into how batch and merge functions with file names and sorting, so unlikely unless it was required to exist. For example:

```yaml
feeds:
- type: release-notes
  changeFormat: "same as change format from root"
  componentFormat: "etc"
  # anything related to how release notes are generated
```

This change would be a pretty major breaking change if required, but to support both would not be too hard for compatibility reasons as it is just moving from one location in the config to a new location.

Anyway, all of this is just an idea that would take a fair amount of work and a bit of configuration on the project side. So, the real question here is, would anyone use this and should it be built and maintained? Also, it would be implied that versions built before any feed configuration was added would not have any feed entry built and you might have to write them manually for existing versions as all the metadata required to build them are lost in the batch process ( unless you use `--keep` ).
