### DISCUSSION TITLE
How can we highlight breaking changes?

### DISCUSSION THREAD

**Discussion by gerhard** [miniscruff/changie#509] [Q&A] [answered]
My understanding of https://keepachangelog.com/en/1.0.0/ is that all `Changed` items are breaking by default since existing functionality changes. Is there a way to make this more obvious?

This does not seem obvious enough:
<img width="1204" alt="image" src="https://github.com/miniscruff/changie/assets/3342/e1e59261-3311-486f-b62c-b6a2dc30b694">

This seems better to me:
<img width="1203" alt="image" src="https://github.com/miniscruff/changie/assets/3342/7cebd63a-1731-408a-8799-1368bf3b43ab">

It would also be important to list the breaking changes first, since they are the most important part of a release for end-users.

Given this starting point - https://github.com/dagger/dagger/blob/62ab7216d8b6f01fe3348778aa909b57dc68d420/sdk/python/.changie.yaml - how would you recommend @miniscruff that we went about this?

---
cc @helderco
👋 @olivierlacan https://changelog.com/podcast/127

**Comment by miniscruff** [comment, marked as answer]
Kinds are in sorted order from the config and can be customized via the https://changie.dev/config/#kindconfig-type options. For your particular question I would do something like:
```yaml
kinds:
  - label: Breaking Changes
    format: '### :fire: **Breaking Changes**'
  - label: Added
  - label: Deprecated
  - label: Fixed
  - label: Dependencies
```

Customize as you wish but just remember the order is preserved and you can separate the prompt label from the final output via the format.
You can also further customize change format or even adding additional prompts only for that kind, eg if you wanted to link to a CVE or something idk.

**Reply by gerhard** [reply]
`format` is **exactly** what I was looking for.

Knowing that ordering is preserved makes this super straightforward.

💯

**Reply by sheldonhull** [reply]
@gerhard a [link to how I do this](https://github.com/DelineaXPM/dsv-cli/blob/main/.changie.yaml) and [example output](https://github.com/DelineaXPM/dsv-cli/releases/tag/v1.39.1). I've played with various go templates and I'm pretty happy with this so far.

Also from the dagger repo, thought I'd mention that the `{{.Component}}` can be used to help define "engine", and other types that you use for your prefixes on each line since you aren't using multi-line entries I see. (body -> block: true). 

That would like sorta like:
```yaml
changeFormat: '- _{{.Component}}_: {{ .Body -}}'
```

**Comment by Blacksmoke16** [comment]
Say I wanted to more strictly adhere to https://common-changelog.org/#244-prefixes that has breaking changes be ordered first within the `Changed` kind. Is there a good way to go about this?

I currently have something like:
```yaml
- label: Changed
  changeFormat: |
    - {{if eq .Custom.Breaking "Yes"}}**Breaking:** {{end}}{{.Body}} ([#{{.Custom.PR}}]) ({{.Custom.Author}})
  additionalChoices:
    - type: enum
      key: Breaking
      label: Is it a breaking change?
      enumOptions:
        - Yes
        - No
```
Which works pretty good so far. Worst case I have to take an extra 2 seconds to manually re-order them (which would be pretty obvious given the prefix). But having a means for that to happen automatically would be even better :sweat_smile:.

**Reply by miniscruff** [reply]
Hm, never heard of common changelog until now surprisingly. Personally, I would just make a separate kind for "breaking" and place it before changed. I find it weird how there could be a non-breaking removed change, but also a change that was just refactoring. Like to me "changed" is always breaking and having to bold it would be easy. Removed would also be breaking. So weird.

Your custom choice is not a bad option though, and just a few reordering lines between batch and merge isn't that bad. Maybe its possible to script it but idk.

**Reply by patricksadowski** [reply]
@Blacksmoke16 How did you adjust the version number depending on the option selected? Breaking changes are usually major versions. I look for a possibility to change "auto" to "major" according to the option selected.

**Reply by Blacksmoke16** [reply]
As of now I just been manually manually specifying if a release is a minor or patch (as my project is pre-1.0) and not making use of `auto`.

**Reply by patricksadowski** [reply]
Ok. I tried different approaches.

## First approach

> Overlapping `format`s does not work.

```yaml
kinds:
  - label: Changed
    auto: patch
  - label: Broken
    auto: major
    format: '### Changed'
    changeFormat: '- **Breaking:** {{.Body}}'
```

but this ends up in 

```markdown
### Changed

- change

### Changed

- **Breaking:** break
```

## Second approach

> Use condition in `auto` does not work.

```yaml
kinds:
  - label: Changed
    auto: '{{if eq .Custom.Breaking "Yes"}}major{{else}}patch{{end}}'
```

## Third approach

> Overlapping `key`s does not work. First defined kind wins.

```yaml
kinds:
  - label: Changed
    auto: patch
    key: changed
    changeFormat: '- {{if eq .Custom.Breaking "Yes"}}**Breaking:** {{end}}{{.Body}}'
  - label: Broken
    auto: major
    key: changed
    post:
      - key: Breaking
        value: "true"
```
