### ISSUE TITLE
Custom configurations per kind

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#118]
This will probably need to be backward incompatible but it would be nice to allow for formatting and choices per kind.

Instead of:
kinds: [string of each kind]

It should be:
```yaml
kinds:
  - label: prompt label
    header: header separate from label
  - repeat
```

Configurations at the top level are default to all kinds with the option to extend or override the defaults per kind.
