### ISSUE TITLE
Replacement with ^ and $ multiline does not work properly

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#180]
### Discussed in https://github.com/miniscruff/changie/discussions/179

<div type='discussions-op-text'>

<sup>Originally posted by **sdurrheimer** November  9, 2021</sup>
Hi @miniscruff,

I'm trying the [`replacements`](https://changie.dev/config/replacements/) feature to change the version within my Helm `Chart.yaml` file.

The file presents itself as the following:
```yaml
version: 0.1.0

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-mysql
    version: ~8.8.8
    condition: mysql.enabled
```

If I use the following configuration, the main version and dependency version are changed:
```yaml
replacements:
- path: Chart.yaml
  find: 'version: .*'
  replace: 'version: {{.VersionNoPrefix}}'
```

But If I do the following to make sure the line strictly start with the `version` string without spaces in front of it, the replacement doesn't happen at all:
```yaml
replacements:
- path: Chart.yaml
  find: '^version: .*'
  replace: 'version: {{.VersionNoPrefix}}'
```

How can I make this work properly?</div>
