### ISSUE TITLE
Normalize and standardize newlines when batching

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#238]
New lines are starting to become a headache around when changie adds them compared to when they are expected from formats, files or anything else. This may introduce visual differences but I do not think it is backwards incompatible and can be done in a minor release.

Solution 1:
~~Remove all manual new lines and expect files and inputs to be handled by the end user~~

Solution 2:
~~Add a newline before and after all supplied files and formatting~~

Solution 3:
~~Create configurations for when to add new lines and when not to, for example before + after headers, footers, changes, kinds, components, etc~~

Solution 4:
~~Create configurations but only for files and templates.~~

Solution 5:
Just like solution 3 but with numbers instead of bools... just cause you might want to have more than one empty line.

Solution 5 works the best, a separate "Newline" section to config would make the most sense.
Something like:
```yaml
Config:
  Newlines:
    BeforeVersion: 0
    AfterVersion: 1
    BeforeComponent: 1
    AfterHeaderFile: 0
    AfterFooterFile: 0
    ... etc
```

**Comment by jonatan5524** [comment]
As I mentioned in https://github.com/miniscruff/changie/issues/119#issuecomment-1133744100 I have some questions, maybe I misunderstood the format:
Newlines configs should be in the .changie.yaml, If so where is it fit in the yaml file?

**Comment by miniscruff** [comment]
I was thinking the later with some capitalization changes, to match typical yaml key values.
```
newlines:
 beforeVersion: 0
 afterVersion: 1
 beforeComponent: 1
 afterHeaderFile: 0
 afterFooterFile: 0
```
