### ISSUE TITLE
support replacements in external files during merge

### ISSUE THREAD

**Issue by miniscruff** [miniscruff/changie#34]
Updating the changelog file acts as the point of "this is a now a new version" but many projects have version fields in other places that should update at the same time. Some examples are package.json for javascript, setup.py for python packages, sphinx packages have a version value, etc. Goreleaser allows using ldflags as build parameters which can be injected from changie latest. 

Configuration:
```yaml
replacements:
- path: file/path.ext
  find: '  "version": ".*",' # regex search each line in file
  replace: '  "version": "{{.VersionNoPrefix}}",' # go template line replacement
```

For a javascript package.json:
```json
{
  "name": "test-project",
  "version": "1.0.0",
  "description": "changie project",
  "main": "src/main.js",
}
```

Replace Struct:
```go
type ReplaceData struct {
    Version string  // original version
    VersionNoPrefix string // no v prefix if version had it
}
