### ISSUE TITLE
Add a format option for custom inputs

### ISSUE THREAD

**Issue by emmyoop** [miniscruff/changie#352]
**Is your feature request related to a problem? Please describe.**
I have a lot of complex logic involved with formatting my changelog based on kind and custom key that could be eliminated if I could format when generating the yaml.

**Describe the solution you'd like**
I'm not sure how you would refer to it but something like the following so that I could then refer to `.Custom.Issue` in multiple other places without having to build the link everywhere.  I have an added step of complexity where I can refer to two different repos so the value of `repo-name` is dynamic.  It's determined by the Kind so I would actually need to be able to define the custom format per kind.

```yaml
custom:
  - key: Issue
    label: GitHub Issue Number
    type: string
    customFormat: ([repo-name/#{{.this.input}}](https://github.com/dbt-labs/dbt-docs/issues/{{.this.input}})
```

**Describe alternatives you've considered**
Continuing to use the more complex templating I'm using.  It works 😃 

**Additional context**
