### ISSUE TITLE
Add CLI vars

### ISSUE THREAD

**Issue by emmyoop** [miniscruff/changie#372]
**Is your feature request related to a problem? Please describe.**
We first added changie to our core repo.  We list all contributors in the footer of every changelog.  Our definition of a contributor is someone _not_ on our team.  To ensure we don't list our internal team as contributors we have a hardcoded list of GitHub handles in the `.changie.yaml` to filter our core team members.  Every time a team member would leave or join, we have to go in to modify this list to ensure it stays up to date.

After using changie for a few months we decided to expand to use on multiple other repos within our org.  Now, when team members change, we have to go update multiple repos with just a handle add or removal.  We no longer have a single source of truth and it is easy for this list to get out of sync.

**Describe the solution you'd like**
We have automated our changelog generation with GitHub Actions.  Where I would ideally like to go with this is to be able to query the GitHub Group membership for my team in previous workflow step and grab the members that way.  Then pass that list in as a CLI argument (`--vars` ?) that I can then access in `.changes.yaml`.

Not sure of the exact syntax but something to this effect:
```bash
changie batch --vars '{"core-team": "user1 user2 user3"}
```

This would allow for a single source of truth as to who our team members are.

**Describe alternatives you've considered**
Continuing to maintain the list in multiple places.

**Additional context**
I think it's important to note the `.changes.yaml` files have differences between the repos as we require different `kinds`.

**Comment by miniscruff** [comment]
I was thinking about something sort of similar for a little while so here is my idea.

Two new configuration options related to using environment variables.
```yaml
env:
    system: true/false # if true, load all environment variables
    prefix: CHANGIE_ # if set, load variables that have this prefix, removing the prefix before storing it
```

Then, all template structs would include a new variable `Env` such that you can do `{{ env.CORE_TEAM }}` however you see fit.

More of a full example:
```yaml
env:
    prefix: CHANGIE_
versionFormat: "{{.Version}} for {{.Env.PROJECT_NAME}}"
```

```sh
export CHANGIE_PROJECT_NAME=Changie
changie batch patch
```

I think it also makes sense to add a section of env to store vars directly in the config like:
```
env:
    define:
        REPO_NAME: dbt-core
```
Then you can use `{{Env.REPO_NAME}}` in the changie config in place of copy pasting dbt-core around. And if you reuse a similar file across projects you just need to change one value instead of many.

We could add a `--vars KEY=Value` similar to how `--custom` is defined if that works as well, but it would work on top of the envs above.

Not entirely sure on specific keys for `env` just yet but this sort of idea should solve your issue. But let me know if not.

**Comment by miniscruff** [comment]
Ok after a little more thought, loading all system env vars is probably not a good idea for now, maybe if someone asks for it. 
And instead of `env.define` I think just using `env` for custom defined env vars would be fine and a value for `envPrefix` would work.

```yaml
envPrefix: CHANGIE_ # empty by default and if not defined, no env vars will be loaded
env:
    PROJECT_NAME: dbt-core # changie config wide values you can use in place of copy paste
```

```sh
# --env would add to the env map[string]string so they would be interchangable
# cli would override existing keys in config
changie new/batch/merge? --env KEY=VALUE
```
