### ISSUE TITLE
changie batch should throw a better error message when a change entry yaml is invalid yaml

### ISSUE THREAD

**Issue by rocktavious** [miniscruff/changie#554]
**Description**
Using the latest version of changie seems to have broken our deployment pipeline.  We run `changie batch v2023.10.20` today and we get the following error

```
yaml: line 2: mapping values are not allowed in this context
```

This worked on our last release v2023.10.3

**What happened**
```
yaml: line 2: mapping values are not allowed in this context
```

**Expected behavior**
To create the batch of changes

**Additional context**
Here is the `.changie.yaml` we are using

```
changesDir: ".changes"
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{.Time.Format "January 02, 2006"}}](https://github.com/OpsLevel/opslevel-go/compare/{{.PreviousVersion}}...{{.Version}})'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
kinds:
- label: Bugfix
- label: Feature
- label: Security
- label: Refactor
- label: Deprecated
- label: Removed
- label: Docs
- label: Dependency
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
envPrefix: CHANGIE_
```
