### ISSUE TITLE
Feature Request: Enhanced Changelog Format Options

### ISSUE THREAD

**Issue by ArvinJ-H** [miniscruff/changie#608]
**Is your feature request related to a problem? Please describe.**
not really

**Describe the solution you'd like**
Currently, Changie supports a standard changelog format, but I'm interested in having additional formatting options to cater to different project structures (monorepo). Specifically, I propose two new formats:

### Plugin/Module-Centric Format:

```
## Plugin-name
## Plugin-name/Module-name
### Added
- Thing added
- Thing added
### Fixed
- Thing fixed
- Thing fixed
```
or

### Category-Centric Format with Module Reference:

```
### Added
- Module1: Thing added
- Module2: Thing added
### Fixed
- Module1: Thing fixed
- Module2: Thing fixed
```
**Describe alternatives you've considered**
Each project have their own changelog, run `changie batch` as normal, but replace `changie merge` with a custom script

**Additional context**
Closed the other two ticket since they are no longer applicable.

**Comment by miniscruff** [comment]
I believe the first one is already possible by using components. I can make an example for you later if needed. And the latter might be possible by adding the component to the change format and skipping the component format. Again, I can try it tomorrow.

**Comment by miniscruff** [comment]
Right, components are configured per project if you are using both. However during the merge process we still generate separate changelogs. If you only want to build one changelog you would not use projects, maybe you would use components instead. 

I'm not sure I fully understand what you want the final output to be as what I was going to suggest is what you tried.

It sounds like you are using a monorepo, but want a single changelog where components determine which app or system the change took place in. Which is possible using components, without projects. 

If the apps are independently released and thus have separate changelogs, you can use the projects feature to handle that. But you will get one changelog per project.

There is not a way to create one changelog while using projects as the whole point of that config is to generate multiple changelogs.

**Comment by ArvinJ-H** [comment]
ah I see what you mean, sorry it was a bit confusing. 

Is it possible to have each project have it's own components?

ie. 
```
projects:
  - label: 
    key: u1
    changelog: ui/u1/CL.md
    components:
    - u1-1
    - u1-2
    - u1-3
  - label: u2
    key: u2
    changelog: ui/u2/CL.md
     components:
    - u2-1
    - u2-2
    - u2-3
  - label: plugin
    key: plugin
    changelog: CHANGELOG.md
     components:
    - p1-1
    - p1-2
    - p1-3
```
