### ISSUE TITLE
kind label vs key

### ISSUE THREAD

**Issue by sheldonhull** [miniscruff/changie#672]
So is the new behavior supposed to use the label value for the templating output and the key for the file name? The file name behavior is working great, but when doing the batch auto commands it uses the key value still not the nice label format.

I'm on latest `changie version v1.19.0`, so checking to make sure I'm not missing something. I still use the `{{.Kind}}` in the templating right? (I've gone through the code for a quick scan and this seems to be correct if I'm following the desired behavior right.

**Comment by miniscruff** [comment]
Not quite sure I follow, are you asking about the kind header of the release notes? This is from the changie config itself.
```yaml
kinds:
  - label: ✨ Added
    key: added
    auto: minor
  - label: 🔥 Changed
    key: changed
    auto: major
  - label: ⚰️ Deprecated
    key: deprecated
    auto: minor
  - label: 🗑️ Removed
    key: removed
    auto: minor
  - label: 🪲 Fixed
    key: fixed
    auto: patch
  - label: 🦺 Security
    key: security
    auto: patch
```
The header is using label but the filename uses key.
Might need more details to reproduce.
