### ISSUE TITLE
Error when creating and merging changelog entries with projects

### ISSUE THREAD

**Issue by Valgard** [miniscruff/changie#743]
**Description**
I encountered issues when using `changie` to create and merge changelog entries:

1. **Creating a Changelog Entry:**
   - When I attempt to create a new changelog entry with the command `changie new`, I receive the following error message: `Error: project missing but required`.
   - This error occurs despite having projects defined in the configuration file.
   - However, if I specify the project using the `-j` parameter, I can successfully create the changelog entry without any issues.

2. **Merging Changelog Entries:**
   - When I attempt to merge changelog entries using the command `changie merge`, I encounter the following error message: `Error: reading files from '.changes/backend': open .changes/backend: no such file or directory`.

**Reproduction Steps**
1. Run changie new without specifying a project using `-j`.
2. Observe the error message regarding the missing project.
3. Run `changie new -j <project-name>` to create an entry successfully.
4. Attempt to merge entries with `changie merge`.
5. Observe the error regarding the missing directory.

**Expected behavior**
* The `changie new` command should create a changelog entry without requiring the `-j` parameter
* The `changie merge` command should successfully merge changelog entries without directory errors.

**Additional context**
* changie version v1.21.0
* Environment: macOS 15 / Homebrew
* .changie.yml
  ```yaml
  changesDir: .changes
  unreleasedDir: unreleased
  headerPath: header.tpl.md
  changelogPath: CHANGELOG.md
  versionExt: md
  versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
  kindFormat: '### {{.Kind}}'
  changeFormat: '* {{.Body}}'
  envPrefix: CHANGIE_
  projectsVersionSeparator: ': '
  projects:
    - label: Backend
      key: backend
      changelog: apps/backend/CHANGELOG.md
    - label: Frontend
      key: frontend
      changelog: apps/frontend/CHANGELOG.md
    - label: Common
      key: common
      changelog: packages/common/CHANGELOG.md
  kinds:
    - label: Added
      auto: minor
    - label: Changed
      auto: patch
    - label: Deprecated
      auto: minor
    - label: Removed
      auto: major
    - label: Fixed
      auto: patch
    - label: Security
      auto: patch
  newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
  ```
