### ISSUE TITLE
Docker image doesn't support non ascii characters #752

### ISSUE THREAD

**Issue by johnraz** [miniscruff/changie#753]
**Description**
If you configure changie to use emoji's or non ASCII character like e.g: é in one of the label, any command that generate a file will crash

Great tool by the way 😉 

**Reproduction Steps**
1. Edit your configuration to look like this:
```
changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
kinds:
    - label: ✨ Added
      auto: minor
    - label: 🔥 Changed
      auto: major
    - label: ⚰️ Deprecated
      auto: minor
    - label: 🗑️ Removed
      auto: minor
    - label: 🪲 Fixed
      auto: patch
    - label: 🦺 Security
      auto: patch
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
```
2. Make sure to add a new change `changie new`
2. Run  `changie batch auto`

**What happened**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x79e3e2]

goroutine 1 [running]:
github.com/miniscruff/changie/cmd.(*Batch).WriteChanges(0xc0001b2000, {0xc0001b20f0?, 0x2f?, 0x1b6?})
	/home/runner/work/changie/changie/cmd/batch.go:428 +0x8e2
github.com/miniscruff/changie/cmd.(*Batch).Run(0xc0001b2000, 0xc0001b0308, {0xc00002b4e0?, 0x0?, 0x0?})
	/home/runner/work/changie/changie/cmd/batch.go:280 +0x630
github.com/spf13/cobra.(*Command).execute(0xc0001b0308, {0xc00002b4b0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b0008)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/home/runner/work/changie/changie/main.go:17 +0x74
```

**Expected behavior**
The file should be generated without error
